# Generated by Django 3.1.3 on 2020-12-09 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Have_a_W2', models.BooleanField()),
                ('annual_Income', models.CharField(max_length=100)),
                ('family', models.DecimalField(decimal_places=5, max_digits=5)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_Number', models.DecimalField(decimal_places=10, max_digits=10)),
                ('street_Address', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state_Abb', models.CharField(max_length=2)),
                ('zipCode', models.DecimalField(decimal_places=6, max_digits=6)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
