# Generated by Django 3.1.3 on 2020-12-09 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_auto_20201209_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeForm',
            new_name='IncomeModel',
        ),
        migrations.RenameModel(
            old_name='PersonalForm',
            new_name='PersonalModel',
        ),
    ]
