# Generated by Django 3.1.3 on 2020-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20201209_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='family',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='personalmodel',
            name='phone_Number',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personalmodel',
            name='zipCode',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
