# Generated by Django 3.1.3 on 2020-12-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201209_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomemodel',
            name='annual_Income',
            field=models.CharField(default="['0']", max_length=100),
        ),
    ]
